/*
Purpose: Build container image with Azure CLI and Terraform installed.
         The image will be used for running the "load-test" Jenkins pipeline job.
Build docker image from jenkins/docker-ci/Dockerfile
Push the docker image to artifactory.cloud.cms.gov/jmeter-aci-docker-local/azcli-tf
*/

pipeline  {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: dind
spec:
  containers:
  - name: dind
    image: artifactory.cloud.cms.gov/docker/docker:20.10.12-dind
    imagePullPolicy: Always
    tty: true
    securityContext:
      privileged: true
    volumeMounts:
      - name: docker-graph-storage
        mountPath: /var/lib/docker
  volumes:
    - name: docker-graph-storage
      emptyDir: {}
"""
    }
  }
  
  environment {
      ARTIFACTORY = 'artifactory.cloud.cms.gov'
      DOCKER_REGISTRY = 'jmeter-aci-docker-local'
      DOCKER_IMAGE = 'azcli-tf'
  }
     
  stages {
    stage('Build') {
	  steps {
	    container('dind') {
		  sh '''
		    cd jenkins/docker-ci
            docker build -t ${DOCKER_IMAGE} .
            docker images
		  '''
        }
      }
    }
    stage('Push') {
	  steps {
	    container('dind') {
	      withCredentials([usernamePassword(credentialsId: 'artifactory', 
	                                        usernameVariable: 'USER', 
	                                        passwordVariable: 'PASS')]) {
		    sh '''
		      docker login ${ARTIFACTORY} -u $USER -p $PASS
              docker tag ${DOCKER_IMAGE}:latest ${ARTIFACTORY}/${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest
              docker tag ${DOCKER_IMAGE}:latest ${ARTIFACTORY}/${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${BUILD_NUMBER}		      
              docker push ${ARTIFACTORY}/${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest
              docker push ${ARTIFACTORY}/${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${BUILD_NUMBER}
		    '''
	      }
        }
      }
    }     
  }
}  